name: Build static rtl_433 for Alpine Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux-static:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install dependencies
        run: |
          apk add --no-cache \
            git \
            build-base \
            cmake \
            libtool \
            autoconf \
            automake \
            pkgconfig

      - name: Checkout rtl_433
        uses: actions/checkout@v4

      - name: Build libusb (static with -fPIC)
        run: |
          git clone https://github.com/libusb/libusb.git
          cd libusb
          ./bootstrap.sh
          CFLAGS="-fPIC" ./configure --enable-static --disable-shared --prefix=/usr
          make
          make install
          cd ..

      - name: Build librtlsdr (disable udev, build static)
        run: |
          git clone https://github.com/steve-m/librtlsdr.git
          cd librtlsdr
          mkdir build
          cd build
          cmake \
            -DBUILD_STATIC=ON \
            -DBUILD_SHARED_LIBS=OFF \
            -DDETACH_KERNEL_DRIVER=OFF \  # disables libudev dependency
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_INSTALL_PREFIX=/usr \
            ..
          make
          make install
          cd ../..

      - name: Build rtl_433 (statically linked)
        run: |
          mkdir build
          cd build
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_DEMOD_OOK=ON \
            -DENABLE_DEMOD_FSK=ON \
            -DENABLE_ANALYZER=ON \
            -DENABLE_RTLSDR=ON \
            -DENABLE_USB=ON \
            -DBUILD_TESTING=OFF \
            ..
          make -j$(nproc)

      - name: Upload rtl_433 binary
        uses: actions/upload-artifact@v4
        with:
          name: rtl_433-static-linux
          path: build/src/rtl_433
