name: Build rtl_433 for Windows and Alpine Linux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install make -y
        choco install mingw -y

    - name: Add MinGW to PATH
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ..
        mingw32-make

    - name: Upload Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: rtl_433_windows
        path: build/rtl_433.exe

  alpine:
    name: Build Alpine Linux Binary
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
    - name: Install build dependencies
      run: |
        apk add --no-cache build-base cmake git libusb-dev

    - name: Clone rtl_433 repo and build
      run: |
        git clone https://github.com/8OND007/rtl_433.git
        cd rtl_433
        mkdir build
        cd build
        cmake -DBUILD_STATIC=ON ..
        make

    - name: Upload Alpine binary
      uses: actions/upload-artifact@v4
      with:
        name: rtl_433_alpine
        path: rtl_433/build/rtl_433
