jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies (build tools)
        run: |
          apk update
          apk add build-base cmake autoconf automake libtool pkgconfig

      - name: Build static libusb without udev
        run: |
          git clone https://github.com/libusb/libusb.git
          cd libusb
          ./autogen.sh
          ./configure --disable-udev --enable-static --disable-shared
          make -j$(nproc)
          make install
          cd ..

      - name: Build static librtlsdr without udev
        run: |
          git clone https://github.com/steve-m/librtlsdr.git
          mkdir librtlsdr/build
          cd librtlsdr/build
          cmake .. -DENABLE_UDEV=OFF -DENABLE_SHARED=OFF -DENABLE_STATIC=ON
          make -j$(nproc)
          make install
          cd ../..

      - name: Build static rtl_433
        run: |
          mkdir -p rtl_433/build
          cd rtl_433/build
          cmake .. -DRTLSDR_STATIC=ON -DLIBUSB_STATIC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static" -DCMAKE_PREFIX_PATH=/usr/local
          make -j$(nproc)
          cd ../..

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rtl_433_static
          path: rtl_433/build/src/rtl_433
