name: Build rtl_433 static Alpine Linux binary

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config cmake git

      - name: Build static libusb without udev
        run: |
          git clone https://github.com/libusb/libusb.git
          cd libusb
          ./autogen.sh
          ./configure --disable-udev --enable-static --disable-shared
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Build static librtlsdr without udev
        run: |
          git clone https://github.com/steve-m/librtlsdr.git
          mkdir -p librtlsdr/build
          cd librtlsdr/build
          cmake .. -DENABLE_UDEV=OFF -DENABLE_SHARED=OFF -DENABLE_STATIC=ON
          make -j$(nproc)
          sudo make install
          cd ../..

      - name: Build static rtl_433 binary
        run: |
          mkdir -p rtl_433/build
          cd rtl_433/build
          cmake .. -DRTLSDR_STATIC=ON -DLIBUSB_STATIC=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static" -DCMAKE_PREFIX_PATH=/usr/local
          make -j$(nproc)
          cd ../..

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: rtl_433-static-binary
          path: rtl_433/build/src/rtl_433
