name: Build rtl_433 Fully Static Alpine Linux Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  alpine_static:
    name: Build Fully Static Alpine Linux Binary
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
    - name: Install build dependencies
      run: |
        apk add --no-cache \
          build-base cmake git autoconf automake libtool pkgconf linux-headers

    - name: Build libusb (static)
      run: |
        git clone https://github.com/libusb/libusb.git
        cd libusb
        ./autogen.sh
        ./configure --enable-static --disable-shared
        make
        make install
        cd ..

    - name: Build librtlsdr (static)
      run: |
        git clone https://github.com/steve-m/librtlsdr.git
        cd librtlsdr
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr ..
        make
        make install
        cd ../..

    - name: Clone rtl_433 repo and init submodules
      run: |
        git clone https://github.com/8OND007/rtl_433.git
        cd rtl_433
        git submodule update --init --recursive

    - name: Build rtl_433 static binary
      run: |
        cd rtl_433
        mkdir build
        cd build
        export PKG_CONFIG_PATH=/usr/lib/pkgconfig
        cmake -DBUILD_STATIC=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS="-static" ..
        make VERBOSE=1

    - name: Verify binary is static
      run: |
        file rtl_433/build/src/rtl_433
        ldd rtl_433/build/src/rtl_433 || echo "Not dynamically linked"

    - name: Upload static Alpine binary
      uses: actions/upload-artifact@v4
      with:
        name: rtl_433_alpine_static
        path: rtl_433/build/src/rtl_433
